[gcp_service_account]
type = "service_account"
project_id = "apexneura-chatbot-project"
private_key_id = "bd1f668ee977fa494e22c3d9cfca48d8a5db912d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3F76xmsSEm8wD
n7oJCDa02g8ZS2gAXg7o+46BUJTQp/Wn0hx/zAwZnNmAu0FuwZsPpgYVgxgBE1We
2lB9SLgeiu5BCp2Gi+GocgjDlmhCkYt/DtNkUfsneO9KB22qGVO4Uwww9Qgbhb81
a3oiu18th9H+PS9wRFLNtDCWU76UUY+sxBulJjJWzrKq1Arutx1tZYjZWWOYwKMV
6/4Rhp3kWw+wDbS1daHIz+t8UCXZlE7iOV78/9pMwai3X2PenL4wm0ywsSe3Kqb5
LPSTzNdwdDIrXS0ZRE1tt5Gdopr/iC9f+KwVooh3rWcKXTXPkI5CZGIQX1gkA6LY
dNBJWfMFAgMBAAECggEAWfQ2Ed82lupOgSdMCNz6t778tRI5rhiIHcpd2MXE34Dt
rf6KVvViqoDH0bnua2J+cuFAUvhd5kVgBxQ+gFcmcocSiG0VOMHn49Dm4mU2oyIL
1ahsjnjCusFtW0MsC2q3GbPfpPv1+EOtTisYThEdsWpt7wmTkYZX4k2Zo3nQg+B7
wYa0EGyVeSJY+iEPz1u1wMMacEzvkNttOG0qNCMhqNTJiNLnXqiLq8QhlD2g5C3U
4pZ8c3HUf9SPy9A4fOH2IIoxcJ+5OSCb0MHSfi/+tvniNpstoRsUw2COqmi0N7zi
JcBZn+03YUwJ8M6xj5uFqMrw+Xb1/GWglGzP7y+8vwKBgQDb8qLKZtFG7QkmcBiO
yeZzTHpBZgEMp6dmwJvySZZ8kvtiez5kCutpcSuD5UDVTsrp+1Aj2hWayw6NLbKM
8tnJWWKMsbsQ7wORjfaUbbzw2ixZv1EvOiQQknG7j4qeT4nGIswXvLMk3zR24Y8G
S674gwTraZ9GNHy5791z62SBRwKBgQDVGpyq391RfHsl/OI6pZB1PKXwit07elHG
vWhq9MoDISImvExBKW73bTGwgb0JM8PEvn6q73jN4da6xmgDFxLC4/rfvIxGS9pi
R3L7TFY3ovH/FRNAtOwK5Aw8sthC54VCcEXvaIgZbHAuun8hCd6Pwxzm+Kyy2L1L
7xJpH7gvUwKBgHM25KOVvGak4DgsXBDgHkGjfB8p6b7RS9V9a7M9bQEQlXJ/EK2j
MrHnQF41BwM15QEwTkiZgtu1Jog5ueAvjnn0wrTknRM/wOTMMrCJ04FvJ/BTUZml
oSK1M7KGfJx1GbyamcKNbGISMg9cFGm914gCSd9vUqmZ8QQNbDm+wsUdAoGBAM2H
5SJI10QIMx3oUKkPlcv8um7M/6KlzslHVLYTceKiyjVh1oniVEv+3LXH63I8osvW
joR+gpzO/DMXuKmCT234Q7YWO5RxBCdVkegdL+ppFc1XnkICPMYkPEkulLWyZiw1
7L2CrAEZPPlUldhflHBDVlTN8oJr1+aspa0OEq5RAoGALb7DjyTL7mSQ77eo3jeN
K1i8+TDzqzEsbn0MOeKnzmHrWe356hJo2nIh4Et1zQZVloIaIocVCLXl+9UIdqWI
/T5qZFy/aPOP0+pit0rrlLK6Crb3i6mOHT9YMF0kRemKBcbcClQfh5Qjh5auPfRc
yxK43PwRR+jwzJS5uDZgBho=
-----END PRIVATE KEY-----"""
client_email = ""apexneura-service-bot@apexneura-chatbot-project.iam.gserviceaccount.com"
token_uri = "https://oauth2.googleapis.com/token"
